### ISSUE TITLE
sheet_to_json: date value is printed the day before

### ISSUE THREAD

**Issue by timratha** [SheetJS/sheetjs#1435] opened 2019-02-22 06:54 UTC
Hi Team,

Recently I am working about reading data which in excel sheet has the value of Date also Value(decimal value).

I am using xlsx -v 0.14.1. My purpose is to get the raw data from the excel file (exact date and value which are filled excel )
 
Sample Data: 
Date                |        Value
12/31/2016     |      -1234567890.12345
12/31/2017     |       1234567890.12345

After I uploaded the excel file, I got: 
**2016-12-30**    -1,234,567,890.12345
**2017-12-30**     1,234,567,890.12345

I find out that the date value is printed the day before. I have checked the value before converting to Json, the date value is **Fri Dec 30 2016 23:59:56 GMT+0700 (Indochina Time)** then once it is converted to Json the value is **2016-12-30**

Is there any solution referring to this case?

**Comment by mareek** [comment] 2019-02-26 10:00
This bug might be linked to #1212. 
Can you try the [fix suggested](https://github.com/SheetJS/js-xlsx/issues/1212#issuecomment-428192053) by @cdmahoney to see if your problem has the same root cause ?

I've created a [pull request](SheetJS/ssf#38) to fix the problem

**Comment by SheetJSDev** [comment] 2021-09-17 13:25
This should have been fixed in v0.16.0, please update and report back if there are issues.

**Closed by SheetJSDev** 2021-09-17 13:25 UTC

**Comment by tanishkab** [comment] 2022-03-25 10:25
It is not fixed yet, using 0.16.9 version

**Comment by QuangVinhTran** [comment] 2022-05-15 06:52
it still have the issue at version : 0.18.7

**Comment by Husain010** [comment] 2024-08-21 12:35
Is this still not fixed? I am facing the same error.
