### ISSUE TITLE
json_to_sheet crashes the page when 300K + records are being returned

### ISSUE THREAD

**Issue by kumarr10** [SheetJS/sheetjs#2519] opened 2022-02-09 20:10 UTC
I am trying to use the api json_to_sheet to create excel file on client side/browser. Sheet_to_json seems to error out with this much data. Any help or alternate ? please help

`let jsonData = data.Table;
              let ws = XLSX.utils.json_to_sheet(jsonData);
              var wb = XLSX.utils.book_new();
              XLSX.utils.book_append_sheet(wb, ws);
              XLSX.writeFile(wb, filename + '.xlsx');`

**Comment by reviewher** [comment] 2022-02-09 22:51
Most likely a dupe of #77 .  To be sure, comment out the `XLSX.writeFile` line.  If the process works without crashing the browser, then it is the same as the older issue and you should leave a comment there with the number of rows, number of columns, and number of values that are text / number of numeric values.

**Closed by reviewher** 2022-02-09 22:51 UTC
