### ISSUE TITLE
The exported date is 43 seconds longer

### ISSUE THREAD

**Issue by yangrongzhou** [SheetJS/sheetjs#2350] opened 2021-08-11 16:51 UTC
Test code:
```js
var sheetData = {
    '!ref': 'A1:A2',
    'A1': { v: '2021-08-12 00:00:00', t: 'd', z: 'yyyy-mm-dd hh:mm:ss' },
    'A2': { v: '2021-08-12 00:27:02', t: 'd', z: 'yyyy-mm-dd hh:mm:ss' },
};

var sheetName = 'Sheet1';
var filename = "test.xlsx";

var workbook = {
    SheetNames: [sheetName],
    Sheets: {}
};

workbook.Sheets[sheetName] = sheetData;

XLSX.writeFile(workbook, filename, { compression: true });
```

But the Excel view result is:
> 2021-08-12 00:00:43
> 2021-08-12 00:27:45

My PC timezone is UTC+8.
Maybe this code can help you find the bug:
```
var basedate = new Date(1899, 11, 30, 0, 0, 0);
console.log(basedate.getTimezoneOffset()); // -485
console.log(basedate.toISOString()); // "1899-12-29T15:54:17.000Z"
```
For the date `1899-12-30 00:00:00`, method `getTimezoneOffset` returns 43 seconds less.

**Comment by SheetJSDev** [comment] 2021-08-14 19:06
The date bug is well known, https://github.com/SheetJS/sheetjs/issues/1918#issuecomment-625714551 was a comment from last year.  Closing as dupe of #1565

**Closed by SheetJSDev** 2021-08-14 19:06 UTC
