### ISSUE TITLE
Cannot open xlsx files created by XLSL.writeFile

### ISSUE THREAD

**Issue by icy-fish** [SheetJS/sheetjs#1692] opened 2019-11-27 02:22 UTC
I'm trying to use js-xlsx to generate xlsl files for my Electron app. I followed the [demo](https://github.com/SheetJS/sheetjs/tree/master/demos/angular2#array-of-arrays) and can also create a xlsl file, here is the code:  
```typescript
const data = [
    ["Name", "Age", "Location"],
    ["Bob", 24, "NYC"],
    ["Jason", 30, "LA"]
];
const ws: XLSX.WorkSheet = XLSX.utils.aoa_to_sheet(data);
const wb: XLSX.WorkBook = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
XLSX.writeFile(wb, "SheetJS.xlsx");
```

Everything works fine before opening the generated file with Excel, when Excel warned me that the file cannot be opened, because of invalid file format or extesion. I'm not sure what's wrong about my code, did I miss something?

Here's how my development env goes:  
- OS: Window 10
- Electron: 5.0.1
- Angular: 7.2.15
- xlsx: 0.15.0
- Excel: Microsoft Office Professional Plus 2013

**Comment by reviewher** [comment] 2019-11-27 06:00
The [electron demo](https://github.com/SheetJS/sheetjs/tree/master/demos/electron) roughly appears to do the same thing.  Can you share the generated file?

**Comment by z-pentaleri** [comment] 2020-01-16 18:38
I'm experiencing the same issue trying to run js-xlsx in Chrome.

When running:
```
let wb = XLSX.utils.book_new();
const ws = XLSX.utils.aoa_to_sheet([
    ["Name", "Age", "Location"],
    ["Bob", 24, "NYC"],
    ["Jason", 30, "LA"]
]);
XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
XLSX.writeFile(wb, "SheetJS.xlsx");
```

I get: [SheetJS.xlsx](https://github.com/SheetJS/sheetjs/files/4073103/SheetJS.xlsx) (attached)

I seem to be able to export any non-zipped format just fine (CSV, FODS, XLS), but zipped formats (ODS, XLSX) have failed every time.

**Comment by SheetJSDev** [comment] 2020-01-16 20:22
How are you loading the library?

using the cdnjs library reproduces the problem: https://jsfiddle.net/sheetjs/619v2foj/

using the unpkg library generates valid files: https://jsfiddle.net/sheetjs/v1atwjo3/

**Comment by z-pentaleri** [comment] 2020-01-17 03:21
I'm importing xlsx.full.min.js. The exact way I'm loading it (if at all relevant) is as a library file in NetSuite.

**Comment by z-pentaleri** [comment] 2020-01-28 20:30
Looking back into this issue, I realized that I actually used `xlsx.min.js`. Using a fully updated `xlsx.full.min.js` (the copy I had from two weeks ago still seemed to fail) solves the issue, but it's still present with `xlsx.min.js`.

**Comment by SheetJSDev** [comment] 2020-01-28 20:36
Can you check if it works using `xlsx.mini.min.js`?  XLSX export should work using the mini build.

**Comment by houke** [comment] 2020-04-03 10:03
I can confirm that when using `xlsx.mini.min.js';` the export works (I had the same issue as OP when importing the whole version `xlsx`)

**Comment by maitsarv** [comment] 2020-08-10 13:02
Mini version has a different implementation of `zip_add_file()` function, that seems to be the root cause of it.

**Comment by voxsoftware** [comment] 2021-02-27 02:04
> I solved the problem with this
> `XLSX.writeFile (wb," SheetJS.xls ");`
> 
> When you write the file, the last line of your code, you must change `XLSX.writeFile (wb," SheetJS.xlsx ");` **To** `XLSX.writeFile (wb, 'book.xls')`
> In other words, change the format of the xlsx file to xls

This is not useful. Why use old format xls?

**Comment by kennydifiore** [comment] 2021-03-09 03:32
Seeing a similar issue on XLSX files created with sheetjs library on Android 10 in a React Native environment:
```
Archive:  Export Schedule w_o Allow List Assessments-5.xlsx
warning [Export Schedule w_o Allow List Assessments-5.xlsx]:  208 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [Export Schedule w_o Allow List Assessments-5.xlsx]:  reported length of central directory is
  -208 bytes too long (Atari STZip zipfile?  J.H.Holm ZIPSPLIT 1.1
  zipfile?).  Compensating...
 extracting: docProps/core.xml       
 extracting: docProps/app.xml        
 extracting: xl/worksheets/sheet1.xml  
 extracting: xl/workbook.xml         
 extracting: xl/theme/theme1.xml     
 extracting: xl/styles.xml           
 extracting: [Content_Types].xml     
 extracting: _rels/.rels             
 extracting: xl/_rels/workbook.xml.rels  
```

**Comment by matthewlamhk01** [comment] 2021-06-07 06:37
I got the same issue, fixed by using `xlsx/dist/xlsx.full.min` instead of 'xlsx' or 'xlsx.mini'

**Comment by hypercubex** [comment] 2021-06-07 06:44
I got the same issue, fixed by using xlsx/dist/xlsx.full.min instead of 'xlsx' or 'xlsx.mini'

**Comment by SheetJSDev** [comment] 2021-09-08 01:03
The core issue here is that using `xlsx.min.js` directly in a browser environment does not work by itself.  For standalone scripts, use the bundled `mini` or `full` script.

@kennydifiore please raise a new issue with a little more detail (like how you are importing in react-native) and we can take a closer look

**Closed by SheetJSDev** 2021-09-08 01:03 UTC

**Comment by berbersky** [comment] 2024-07-17 17:20
### Same problem while importing in react !


`import * as XLSX from "xlsx";`

`const handleExport = () => `

`{`
 `      const worksheet = XLSX.utils.json_to_sheet(data)`
`       XLSX.utils.sheet_add_aoa(worksheet, [Object.values(forestFireColumsNamesAR)]);`

`       const workbook = XLSX.utils.book_new();`
`       XLSX.utils.book_append_sheet(workbook, worksheet, "Forest Fire 2017");`

`       XLSX.writeFile(workbook, "table_data.xlsx"); `
`      // Or  XLSX.writeFileXLSX(workbook, "table_data.xls");  Both the same`
`}`


the exported file can't be opened in MS Office 2021, but in Google Sheets, is just fine.
