### ISSUE TITLE
x-spreadsheet demo cannot work 

### ISSUE THREAD

**Issue by samz-github** [SheetJS/sheetjs#2158] opened 2020-10-26 10:24 UTC
I try to see if https://oss.sheetjs.com/sheetjs/x-spreadsheet.html work, but it failed. Thrown exception on console as below:
> x-spreadsheet.html:54 Uncaught ReferenceError: x is not defined
>     at x-spreadsheet.html:54

**Comment by michaeltomasik** [comment] 2020-10-26 21:47
duplicate of https://github.com/SheetJS/sheetjs/issues/2133

**Closed** 2020-10-26 21:59 UTC

**Comment by reviewher** [comment] 2021-09-12 02:25
428d03a4692e1a96e9e6aa4488de95af397ff77c
