### ISSUE TITLE
I want toolbar feature，support it？

### ISSUE THREAD

**Issue by leeseean** [SheetJS/sheetjs#1959] opened 2020-05-21 01:38 UTC
<img src="https://user-images.githubusercontent.com/17198500/82431574-627dd200-9ac1-11ea-9263-19f6148aadbf.png"/>
I want toolbar feature，support it？

**Comment by reviewher** [comment] 2022-02-13 00:17
Duplicate of #1722

**Closed by reviewher** 2022-02-13 00:17 UTC
