### ISSUE TITLE
Feature Request: sheetRowsOffset option for reading in batches or pages

### ISSUE THREAD

**Issue by agu-z** [SheetJS/sheetjs#1887] opened 2020-04-01 21:58 UTC
I'm trying to read a big file (over 200K rows) but I can't do it all once because I quickly run out of memory. Instead, I would like to read it in batches, but AFAIK there's no way to do this. 

The `sheetRows` option allows you to limit how many rows to parse, but there's no way to specify where to start. It'd be great if you could pass a `sheetRowsOffset` option.

I'd be happy to send a PR but I'd need some guidance. It looks like `sheetRows` is referenced from many different functions. Should `sheetRowsOffset` be used in the same places to slice the file properly?

**Comment by reviewher** [comment] 2021-09-20 06:25
Duplicate of #475 please follow up there

**Closed by reviewher** 2021-09-20 06:25 UTC
