### ISSUE TITLE
Wrongly parsing csv string cell as date

### ISSUE THREAD

**Issue by filipelbc** [SheetJS/sheetjs#940] opened 2018-01-03 18:13 UTC
When reading a CSV string, some fields that should be parsed as strings are parsed as dates.

This happens when the string ends with something that resembles a date.

Use the following snippet to reproduce.

```javascript
var foo = 'foo,bar\nfoo2,bar2\n"Wololo thing - ends Feb. 15, 2017","Wololo thing - ends Feb. 15, 2017 bar"';
var w = XLSX.read(foo, {type: "string", cellDates: true});
console.log(w.Sheets.Sheet1);
```

**Expected result:** the third row contains 2 strings:
```javascript
{t: "s", v: "Wololo thing - ends Feb. 15, 2017"}
{t: "s", v: "Wololo thing - ends Feb. 15, 2017 bar"}
```

**Actual result:**  the third row contains
```javascript
{t: "d", v: Wed Feb 15 2017 00:00:00 GMT-0200 (-02), w: "2/15/17"}
{t: "s", v: "Wololo thing - ends Feb. 15, 2017 bar"}
```

**Comment by SheetJSDev** [comment] 2018-01-04 02:45
For plaintext formats like CSV and HTML, the current approach for determining the data type is [testing whether the string represents a valid Date and whether the month is mentioned](https://github.com/SheetJS/js-xlsx/blob/master/bits/20_jsutils.js#L121).  V8 (chrome/nodejs) is extremely lenient in this regard.  You can test in the JS console:

```js
> new Date("Wololo thing - ends Feb. 15, 2017")
Wed Feb 15 2017 00:00:00 GMT-0500 (EST)
```

Realistically, we'll have to pick a small set of explicit formats to test against.

**Comment by brollins90** [comment] 2018-01-25 02:41
We are also seeing this bug.  Is there a way that you are thinking about a fix?  I wouldn't mind working on it if I had some direction.

**Comment by SheetJSDev** [comment] 2018-01-25 18:13
@brollins90 the plaintext (HTML/DSV) date resolution is in the [`fuzzydate` function](https://github.com/SheetJS/js-xlsx/blob/master/bits/20_jsutils.js#L122).  At a high level, a string is converted to a `Date` and the function checks for some known corner cases.  It also inspects the string to see if it's likely to be a date.

The guess is trickier because Excel lets you mix text with date formats.  For example, the string `Today is Jan 25 2018` can be reproduced by setting a cell to `43125` with format `"Today is "mmm dd yyyy`.  Should the string be considered a date or a string?

**Comment by mcdado** [comment] 2018-02-14 01:09
> For example, the string Today is Jan 25 2018 can be reproduced by setting a cell to 43125 with format "Today is "mmm dd yyyy. Should the string be considered a date or a string?

This seems crazy to me! Keep it as a string!!!

This behavior should be disabled on request. I'm importing a CSV to perform corrections and it keeps on converting values like "VIA MARTUCCI 2" to the date "3/2/01", I tried using `raw: true` but it simply uses the number "36952".

**Comment by speedofsound99** [comment] 2018-03-27 13:53
Same problem here. raw: true should mean completely raw results, not raw + parsed dates.

**Comment by johnlop** [comment] 2018-05-18 20:42
I am having the same issue here. A column with IDs like "0002-001-1" gets imported as "2/1/01". I also tried using "raw: true" but I get a weird value: "36892.041666666664"

Is there no way around this?

**Comment by speedofsound99** [comment] 2018-05-22 08:09
I'm using xlsx.read(foo, { type: 'string', raw:true }); and I'm getting the dates in the expected plain text format

**Comment by creedmangrum** [comment] 2019-03-13 18:31
I'm running into this problem when using sheet_to_json and it doesn't appear that I can override to indicate to just bring in the string and not attempt to type it as a `n` or date.

**Comment by d30jeff** [comment] 2019-04-02 16:48
To those who are getting weird number for the date row when using `sheet_to_json` function,
remember to include the `raw: false` option in `sheet_to_json`

```
const workbook = excel.readFile(file.path);

const sheet_name_list = workbook.SheetNames;
const json = excel.utils.sheet_to_json(workbook.Sheets[sheet_name_list[0]], {
  raw: false,
});
```

**Comment by sibelius** [comment] 2020-01-30 13:35
raw: false 

solved for this

**Comment by SystemParadox** [comment] 2020-05-07 09:24
@SheetJSDev there seems to be a lot of issues with dates and the `cellDates` option. I think the major issue here is that `cellDates` causes sheetjs to try and parse everything as a date, including guessing for string cells.

I think this behaviour is wrong. If we're reading in files with string dates (especially CSV files) then it's likely that we know best how to parse them, so leave them alone. But if we're reading in an xlsx file then we need sheetjs to convert that stupid number format into a date for us.

We only have two options at the moment: parse nothing or parse everything. But what we want is to parse everything that's clearly marked as a date (in the **type** information, not by any guessing), and leave everything else alone.

This should be the default behaviour. If we want sheetjs to also try to parse strings into dates we should have to specify an option for that (although I don't see the point of complicating sheetjs with such an option when it's easier to just do this afterwards). If we want to get the raw values for those silly number dates, then we should have to specific an option for that (either `raw` or a separate option).

There are two key points here:

1. SheetJS should always stick to the specified type. If it's typed as a string, leave it as a string. If it's typed as a number, leave it as a number. If there is no type information, leave it alone! Only if it's specifically typed as a date should any conversion be done.
2. We shouldn't need to call extra utility functions like `xlsx.SSF.parse_date_code` unless there was something wrong with the type information or we specifically requested `raw` mode.

**Comment by SheetJSDev** [comment] 2020-05-07 16:41
Excel does its own date and value parsing from CSV.  To confirm this, save the following to a CSV file and open in Excel:

```
2020-05-07,=YEAR(INDIRECT("A"&ROW()))
="2020-05-07",=TYPE(INDIRECT("A"&ROW()))
"2020-05-07",=TYPE(INDIRECT("A"&ROW()))
2020,=TYPE(INDIRECT("A"&ROW()))
FALSE,=TYPE(INDIRECT("A"&ROW()))
=NA(),=TYPE(INDIRECT("A"&ROW()))
```

Cells A1 and A3 are interpreted as dates, while cell A2 is kept as text.  In fact, you'll notice that the expressions starting with "=" are actually interpreted as formulae rather than text!

`raw: true` lets you skip the whole value parsing logic, giving you the original text that you are free to interpret however you wish.


The root of the problem in this issue is the flexibility of V8 in date parsing.  Consider:

```js
new Date("How many days does it take for Mars to go around the sun? 687")
```

We can probably agree that string isn't a date, but V8 thinks it is Tuesday March 1 in the year 687

**Comment by SystemParadox** [comment] 2020-05-24 20:08
Ok so with `raw:true, cellDates: true` it seems to work how I expect, with the caveat that I also have to parse numbers myself.

I'm really confused by the folks saying they have to use `raw: false` - that's surely the opposite of what you want here?

**Comment by oussama-he** [comment] 2021-04-24 09:55
@SystemParadox your solution works fine. But if there are numbers in others columns they will be prefixed by a single quote. So please there is a fix for this?
![Uploading Screenshot at 2021-04-24 10-55-03.png…]()

**Comment by SystemParadox** [comment] 2021-04-26 07:41
This thread is about parsing CSV files, not writing them so your screenshot doesn't make a lot of sense without some more context as to what you are doing.

I'm assuming you're parsing a file, doing something with it and then writing it back out again. As I said above, in raw mode everything will be a string so you have to convert the numbers yourself. I've just got a simple regex to check for a cell with `[0-9.]+` and convert it with `value = Number(value)`.

**Comment by SheetJSDev** [comment] 2021-09-14 17:34
There are multiple discussions here and it is better to discuss the issues separately.

At a high level, the default behavior should mirror Excel.  That means:

1) Excel performs value parsing of the individual cell texts.

The specific issue of V8 (node/chrome) parsing dates that aren't expected to be dates is covered in https://github.com/SheetJS/sheetjs/issues/2196

@filipelbc this is the original problem.

2) Excel stores a date code (generates a numeric cell) when a Date is parsed.

Under the hood, Excel doesn't really have a Date type.  It is an artificial SheetJS construct based on the XLSX `'d'` type.

Passing `cellDates: true` will general equivalent dates for your timezone.  It's timezone-specific because the date codes themselves are based on the epoch (1900 or 1904) in your local timezone.

@mcdado @johnlop @creedmangrum @d30jeff the weird numbers stem from the default behavior and can be switched by setting `cellDates: true`

. 

@oussama-he that is a property of the export.  The highlighted cell is actually the text "15" (`{t: "s", v: "15"}`).  Check your source data, it may have strings instead of numbers.

.

@SystemParadox there have been loose attempts to try to correct for V8's date robustness.  `fuzzydate` took a heuristic approach of looking for key parts.  Identifying the handful of Date formats that Excel will parse is an alternate approach that should be explored further.

**Closed by SheetJSDev** 2021-09-14 17:34 UTC
Labels: Dates, Read Bug
