### ISSUE TITLE
ws['!cols'] not working for ods

### ISSUE THREAD

**Issue by Raitki** [SheetJS/sheetjs#1454] opened 2019-03-13 12:15 UTC
I am trying to change cols size for ods file but it is not working for some reason, it does work if I export as xlsx.
This what I am doing at the moment:
`const schools = [{wpx:100}, {wpx:50},{wpx:150}];`
...
`const ws = XLSX.utils.aoa_to_sheet(value);`
`const wb = XLSX.utils.book_new();`
`ws['!cols'] = wscols;`
`XLSX.utils.book_append_sheet(wb, ws,  'SpreadSheet');`
`XLSX.writeFile(wb, 'export.ods', {bookType: "ods"});
`
any idea what I am doing wrong? Thank you.

**Comment by Vacalexis** [comment] 2020-02-06 19:21
Hello, any news on this subject? I have the exact same problem. .xlsx works just fine. .ods and .xls not working. Auto-filters are lost as well.

**Comment by vishal80072** [comment] 2021-06-04 09:15
is there any way, we can set column width to 'auto' ??

**Comment by NoviceDuke** [comment] 2021-08-28 03:44
Me too,
I write file .xls
set sheet["!cols"] = [{wpx: 36 },] 
wpx width wch also not work
but set file xlsx is working

**Comment by SheetJSDev** [comment] 2021-08-28 04:15
@vishal80072 the file formats don't have "auto", and calculating the right width in pixels requires knowledge of the base font among other things.

Marking as dupe of #1208

**Closed by SheetJSDev** 2021-08-28 04:15 UTC

**Comment by zp1112** [comment] 2022-03-03 07:19
@NoviceDuke  Did you resolved your problem?When write .csv it did not work

**Comment by dahrougomar** [comment] 2022-11-16 16:21
Did someone find a way to set the width for the columns?

**Comment by OlegDikonsky** [comment] 2023-02-06 14:25
```
let wscols = [
  {wch:10},    //column 1
  {wch:12},    //column 2
  {wch:12},    //column 3
  ];
 ws['!cols'] = wscols;
```

**Comment by SheetJSDev** [comment] 2023-02-06 15:56
@zp1112 width does not currently apply to CSV files.  There are some interesting questions (like how you would pad fields) and that discussion will be tracked in https://git.sheetjs.com/sheetjs/sheetjs/issues/2871

Widths are written to XLS, ODS, XLSX and other formats.  If something is missing, please raise a new issue.
