### ISSUE TITLE
Angular 10 warning message

### ISSUE THREAD

**Issue by yurimarx** [SheetJS/sheetjs#2116] opened 2020-09-25 11:20 UTC
depends on 'xlsx'. CommonJS or AMD dependencies can cause optimization bailouts.

**Comment by LeoLetourneur** [comment] 2020-10-05 12:52
Duplicate of #2023

**Comment by SheetJSDev** [comment] 2021-09-09 07:03
Marking as dupe of #2033

**Closed by SheetJSDev** 2021-09-09 07:03 UTC
