### ISSUE TITLE
Server-side deployed xlsx.writeFile not showing any data

### ISSUE THREAD

**Issue by olishiz** [SheetJS/sheetjs#2357] opened 2021-08-18 04:51 UTC
Hey guys,

I've been working with this library and found out that the writeFile is able to download and show 'data' in my localhost but not in my server-side deployed Angular application. (dev/uat/production) all are affected without any data.

 exportToExcel() {
  const ws: xlsx.WorkSheet =   
  xlsx.utils.table_to_sheet(this.epltable.nativeElement);
  const wb: xlsx.WorkBook = xlsx.utils.book_new();
  xlsx.utils.book_append_sheet(wb, ws, 'Sheet1');
  xlsx.writeFile(wb, 'epltable.xlsx');
 }

I use a similar approach to create a WorkSheet and WorkBook and call the writeFile function in my Angular 9 App.

Is there any reason why this library behave in this way? 

[in localhost data](https://ibb.co/yk50PrX)

[in server-side data](https://ibb.co/TK2Mjn5)

Any help would be greatly appreciated.

**Comment by reviewher** [comment] 2021-08-18 05:13
Please try

```
xlsx.writeFile(wb, 'epltable.xlsx', {WTF:1});
```

and report if it throws an error

**Comment by olishiz** [comment] 2021-08-18 05:28
@reviewher 

Hey buddy, thanks for the notice.

Based on this documentation link, [link (writing-options)](https://docs.sheetjs.com/#writing-options)

It seems that there is no 'WTF' options to be input. And angular app throws error upon compiling lol.

**Comment by reviewher** [comment] 2021-08-18 05:33
The types should work.  Are you using the latest version?  `console.log(xlsx.version)`

- `writeFile` expects a `WritingOptions`: https://github.com/SheetJS/sheetjs/blob/master/types/index.d.ts#L20 
- `WritingOptions` extends `CommonOptions`: https://github.com/SheetJS/sheetjs/blob/master/types/index.d.ts#L203
- `CommonOptions` include the `WTF` field: https://github.com/SheetJS/sheetjs/blob/master/types/index.d.ts#L87

**Comment by olishiz** [comment] 2021-08-18 06:03
Yeah sorry about that. Updated to 0.17.0 and let me give it a try on my server and update here if the issue prevails.

**Comment by olishiz** [comment] 2021-08-18 06:19
Well this is weird..

When I serve my angular application on my localhost using 'ng serve' - it is able to download and show the data as mentioned.

But when I make build - by using this command as in my Makefile:

- npm i && ng build --aot --base-href=/dev/aotg/ --output-hashing=all

And spin up a lite-server and serve using it, it is showing no data when downloading the excel file. (similar experience in my server).

I've checked the logs on my console and it isnt showing any error at all. Any help on this?

**Comment by olishiz** [comment] 2021-08-18 06:36
[this is on my ng serve](https://ibb.co/rdv7Dxd)
[this is on my ng build](https://ibb.co/DfD0qp6)

the difference that im having is that 'worksheet object' on ng build is not similar with ng serve..

why is that happening?

**Comment by olishiz** [comment] 2021-08-18 06:39
oh yeah, im using this line of code for the ws, wb

- const ws: XLSX.WorkSheet = XLSX.utils.json_to_sheet(input);
- const wb: XLSX.WorkBook = XLSX.utils.book_new();

input will be the array of objects in my table

**Comment by reviewher** [comment] 2021-08-18 06:40
Can you log the input to make sure they are the same?

**Comment by olishiz** [comment] 2021-08-18 06:46
https://ibb.co/N6WbQ0x
https://ibb.co/8jP0FJJ

I've just double checked and it seems the input data are exactly the same as you can see here. 
port 4200 is my ng serve while port 3000 is my lite-server for ng build

funny thing is the ws object doesnt not recognize any value on my port 3000

**Comment by reviewher** [comment] 2021-08-18 06:54
The object keys in the second screenshot look wrong.  "2" and "3" will not be written.  Can you share the exact code in lines 180 - 188 from `general.service.ts` ?  It looks like the input from line 181 is the same so the issue may be in between

**Comment by olishiz** [comment] 2021-08-18 06:59
[code ss](https://ibb.co/QncHKP3)

here are the codes, its quite straightforward but im really not sure where the problem lies

**Comment by reviewher** [comment] 2021-08-18 07:52
Another possibility might be a timing issue, can you log `JSON.stringify(input)` just before the `json_to_sheet` call?

**Comment by olishiz** [comment] 2021-08-18 08:16
Yeah, it seems there are objects.

https://ibb.co/z5XP6Wf

Seems like the root issue would be in here.

const ws: XLSX.WorkSheet = XLSX.utils.json_to_sheet(input);

But it's really weird my local able to capture the json objects but build cant?

**Comment by reviewher** [comment] 2021-08-18 08:34
Let's try a few more things:

1) Try building without `--aot`

2) call

const ws: XLSX.WorkSheet = XLSX.utils.json_to_sheet(JSON.parse(JSON.stringify(input)));

**Comment by olishiz** [comment] 2021-08-18 08:43
Tried it. My initial thought was also 'maybe its the compilation error' but I build without the `--aot`

localhost serve - ok
localhost build - not ok

[image](https://ibb.co/WcsLTRC)

**Comment by olishiz** [comment] 2021-08-18 09:22
Anyway, do you know why it behaves like this? Very weird behavior of the library

[ng serve log debug item](https://ibb.co/8cdbth9)
[ng build log debug item](https://ibb.co/d5vLjKc)

Inputs are definitely the same (2 objects) but the outcome of the ws object is completely different.

When I spec and debug on the item, it doesnt show the exact same thing with both app.. 

[super weird](https://ibb.co/30Yjb1v)

**Comment by olishiz** [comment] 2021-08-19 04:01
Bump. Any takes on this

**Comment by reviewher** [comment] 2021-08-19 06:04
Given that the issue seems to stem from something in Angular, it might make sense to raise an issue with them and see what could be different in the two environments.

**Comment by olishiz** [comment] 2021-08-20 05:32
Have you encountered anyone with the similar problem as well? Maybe it's because of the compiler issue / importing system in my Angular app?

**Comment by reviewher** [comment] 2021-08-20 05:49
This is an issue better addressed by the Angular project, especially since it works in some cases there.  All evidence points to an issue on their end.

**Comment by DerekHill** [comment] 2022-02-24 09:16
We had a similar problem using Vue.js when we imported xlsx in an ESM-style way:

```javascript
import XLSX from 'xlsx';
```

This worked in development, but in production `XLSX.utils.book_new()` never returned.

As the [readme](https://github.com/SheetJS/sheetjs) of this package says:

> By default, the module supports `require`:
> 
> `var XLSX = require("xlsx")`;

When we switched the import to this style it worked in both development and production.

**Comment by reviewher** [comment] 2022-03-04 04:18
@olishiz still can't reproduce the issue with the [`angular2` demo](https://github.com/SheetJS/sheetjs/tree/master/demos/angular2) in ng 13.  `ng build --aot --output-hashing=all` creates files in `dist/sheetjs/` and the export appears to work.  Please try updating to the latest version (0.18.3) and see if that resolves the issue.  If not, please share a sample project or raise the issue with angular devs.

**Closed by reviewher** 2022-03-04 04:18 UTC
