### ISSUE TITLE
file corrupt when using xlsx.min.js but not when using the full or mini version

### ISSUE THREAD

**Issue by micahmills** [SheetJS/sheetjs#1786] opened 2020-03-05 08:37 UTC
I am creating a workbook from a table in HTML. This has been working fine for months using the xlsx.mini.min.js file. When I tried to use the same JS code to generate the excel file using the xlsx.min.js file it gives me the error. "the file format or file extension is not valid. Verify that the file has not been corrupted and that the file extension matches the format of the file." 

To test I used the xlsx.full.min.js file and it out put the file without any corruption issues. So there appears to be a bug in the xlsx.min.js file.

**Comment by SheetJSDev** [comment] 2020-03-05 14:44
Duplicate of https://github.com/SheetJS/sheetjs/issues/1736

**Closed by SheetJSDev** 2020-03-05 14:44 UTC
