### ISSUE TITLE
date format reduce 43 seconds

### ISSUE THREAD

**Issue by fastkdm** [SheetJS/sheetjs#2481] opened 2021-12-23 10:09 UTC
when i use XLSX.read() with {type:'binary',cellText:false,cellDates:true},the value of date reduce 43 second in cell.v

when i try to add 43 second on cell.v.setSeconds(cell.v.getSeconds()+43),the result still error

eg: 
add before:
      cell.v     Sat Dec 11 2021 18:04:17 GMT+0800 (中国标准时间)
      cell.w.   2021-12-11 18:04:00
add after:
      cell.v     Sat Dec 11 2021 18:05:00 GMT+0800 (中国标准时间)
      cell.w.    2021-12-11 18:05:43

i also try to find sth in issues,also see https://github.com/SheetJS/sheetjs/issues/1565,but cant find sth to use

please author , can you show me the code to solve the problem

------------------------------------------------------------------------------------------------------------------------

i try to add 1 millisecond like: cell.v = new Date(cell.v.getTime()+1), the format fixed, i want to know the best method to reslove the problem in the future

**Comment by reviewher** [comment] 2021-12-29 20:43
Dupe of #2350.  Follow #1565 for updates

**Closed by reviewher** 2021-12-29 20:43 UTC
